key:            PublishingPriorities
id:             PublishingPriorities
name:           'Publishing Priorities'
description:    'Fine tune the priority templates and blogs are published with.'
author_name:    'Dan Wolfgang, Endevver'
author_link:    http://endevver.com
plugin_link:    https://github.com/endevver/mt-plugin-publishing-priorities
version:        1.0.2

callbacks:
    # The default build_file_filter callback that handles sending items to the
    # Publish Queue uses the default priority, 5. Setting a higher priority will
    # ensure Publishing Priorities build_file_filter callback runs first.
    build_file_filter:
        handler: PublishingPriorities::Plugin::callback_build_file_filter
        priority: 2

applications:
    cms:
        menus:
            settings:publishing_priorities:
                label: Publishing Priorities
                mode:  publishing_priorities.edit
                order: 500
                view:
                    - blog
                    - website
                permission: administer
            settings:system_publishing_priorities:
                label: Publishing Priorities
                mode:  publishing_priorities.system_edit
                order: 500
                view:
                    - system
                permission: administer
            # MT4
            prefs:publishing_priorities:
                label: Publishing Priorities
                mode:  publishing_priorities.edit
                order: 500
                view:  blog
                permission: administer
            prefs:system_publishing_priorities:
                label: Publishing Priorities
                mode:  publishing_priorities.system_edit
                order: 500
                view:  system
                permission: administer
        methods:
            publishing_priorities.edit:        PublishingPriorities::CMS::edit
            publishing_priorities.save:        PublishingPriorities::CMS::save
            publishing_priorities.system_edit: PublishingPriorities::CMS::system_edit
            publishing_priorities.system_save: PublishingPriorities::CMS::system_save

page_actions:
    list_templates:
        publishing_priorities:
            label: 'Publishing Priorities'
            mode: publishing_priorities.edit
            order: 200
            permission: administer

settings:
    template_priorities:
        scope: system
    blog_priorities:
        scope: system
